### ISSUE TITLE
Gif in sphinx doc with play button?

### ISSUE THREAD

**Issue by stuaxo** [ddbeck/gifs-as-documentation#5]
There seem to be a few javascript libraries that let you have animated gifs with a play button, so they don't play immediately.

Is there a way of using something like this with sphinx-docs?

**Comment by ddbeck** [comment]
@stuaxo Honestly, I'm not sure what the answer is. You might want to ask in the [sphinx-users mailing list](https://groups.google.com/forum/#!forum/sphinx-users). I imagine you're likely to get several responses there. Best of luck sorting it out!

**Comment by stuaxo** [comment]
Cheers - it was a bit of a punt, will try there.
